version: '3.9'
services:
  streamlit:
    build:
      context: .
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
      dockerfile: Dockerfile.seams
    container_name: seams-streamlit
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - ./seams/:/home/user/
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      #- DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - PORT=8501
      - LOCAL_IP=localhost
    command: stramlit run ~/seams/app.py
    networks:
      - seams-network
      #seams-network:
        #ipv4_address: 172.16.238.2

  postgis:
    build:
      context:  .
      dockerfile: Dockerfile.postgis
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    container_name: seams-postgis
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}        
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - seams-network
 

volumes:
  pgdata:

networks:
  seams-network:
    external: true
    # Note that we defined the `seams-network` network as an external network. This assumes that the seams-network network already exists on the host machine, and is shared among multiple Docker Compose files. If the network does not exist yet, 
    # you can create it with the following command on the command propmt:
    # `docker network create seams-network`
    #driver: bridge
    #ipam:
    #  config:
    #    - subnet: 172.16.238.0/24


