[server]
maxUploadSize = 1000
# maxMessageSize = 500
# Set the Streamlit server address to a specific IP
# address = '172.16.238.2'

[theme]
# royal blue
primaryColor =  "#003366"  
# "#00436F"
backgroundColor = "#FFFFFF"
# secondaryBackgroundColor = "#F0F2F6"
textColor= "#003D76"
# "#663300" complementary
# "#212529"
font="sans serif"

